//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Geekiam.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NameCannotBeDomain {
            get {
                return ResourceManager.GetString("NameCannotBeDomain", resourceCulture);
            }
        }
        
        internal static string DomainCannotBeFeedUrl {
            get {
                return ResourceManager.GetString("DomainCannotBeFeedUrl", resourceCulture);
            }
        }
        
        internal static string InvalidDomainName {
            get {
                return ResourceManager.GetString("InvalidDomainName", resourceCulture);
            }
        }
        
        internal static string RelativePathRequired {
            get {
                return ResourceManager.GetString("RelativePathRequired", resourceCulture);
            }
        }
        
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        internal static string InvalidUrlFormat {
            get {
                return ResourceManager.GetString("InvalidUrlFormat", resourceCulture);
            }
        }
        
        internal static string FeedUrlIsRequired {
            get {
                return ResourceManager.GetString("FeedUrlIsRequired", resourceCulture);
            }
        }
        
        internal static string SourceNameIsRequired {
            get {
                return ResourceManager.GetString("SourceNameIsRequired", resourceCulture);
            }
        }
        
        internal static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
    }
}
