name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Check out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run the Cake script
        uses: cake-build/cake-action@v2
        with:
          script-path: build.cake
          arguments: |
            GITHUB_TOKEN: ${{ github.token }}
            NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
     
      - name: Create check run with code coverage Markdown report
        uses: LouisBrunner/checks-action@v1.6.2
        if: always()
        with:
          token: ${{ github.token }}
          name: Code Coverage Summary
          conclusion: ${{ job.status }}
          output: '{"summary":"Geekiam Feeds Database Code Coverage Summary"}'
          output_text_description_file: coverage/summary/SummaryGithub.md
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
           name: nuget-packages
           path: artifacts
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Run the Cake script
        uses: cake-build/cake-action@v2
        with:
          script-path: publish.cake
          arguments: |
            GITHUB_TOKEN: ${{ github.token }}
            NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}  
      