name: nuget-build-deploy
on:
  push:
    branches:
      - release/**
  pull_request:
    branches:
      - release/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Check out Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run cake
        shell : bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          dotnet new tool-manifest
          dotnet tool install Cake.Tool
          dotnet tool restore
          dotnet cake